import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ReduxProvider from "@/store/redux-provider";
import Navbar from "./navbar/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en" className='h-full bg-orange-100'>
        <body className={inter.className} style={{ 'height': '100%' }}>
            <ReduxProvider>
                <main>
                    <Navbar />
                    {children}
                </main>
            </ReduxProvider>
        </body>
      </html>
  );
}
