import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ReduxProvider from "@/store/redux-provider";
import Navbar from "./navbar/page";
import { ToastContainer } from "react-toastify";
import 'react-toastify/dist/ReactToastify.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-orange-100">
      <body className={inter.className}>
        <ReduxProvider>
          <main>
            <Navbar />
            <div className="w-full h-full justify-center">{children}</div>
            <ToastContainer position="top-center" autoClose={3500} />
          </main>
        </ReduxProvider>
      </body>
    </html>
  );
}
